-- WorshipFlow - schema PostgreSQL/Supabase
-- Origem: database/worshipflow.sql (MariaDB/MySQL)
-- Uso: execute este arquivo em um banco PostgreSQL limpo antes dos seeds.

BEGIN;

CREATE TABLE IF NOT EXISTS ministerios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  descricao VARCHAR(500),
  ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS musicas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(140) NOT NULL,
  artista VARCHAR(120),
  tonalidade VARCHAR(12),
  bpm INTEGER,
  link_cifra VARCHAR(500),
  ministerio_id BIGINT,
  CONSTRAINT fk_musicas_ministerios
    FOREIGN KEY (ministerio_id) REFERENCES ministerios(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  habilidades VARCHAR(300),
  status_ministerio VARCHAR(30) NOT NULL,
  email VARCHAR(160) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  telefone VARCHAR(30),
  instrumento_principal VARCHAR(80),
  perfil VARCHAR(30) NOT NULL,
  reset_token_hash VARCHAR(128),
  reset_token_expira_em TIMESTAMP(6),
  api_token_hash VARCHAR(128),
  api_token_expira_em TIMESTAMP(6),
  foto_perfil TEXT,
  foto_perfil_tipo VARCHAR(60),
  ministerio_id BIGINT,
  CONSTRAINT uk_usuarios_email UNIQUE (email),
  CONSTRAINT chk_usuarios_status_ministerio
    CHECK (status_ministerio IN ('ATIVO', 'BLOQUEADO', 'DESLIGADO', 'EM_PAUSA', 'INATIVO')),
  CONSTRAINT chk_usuarios_perfil
    CHECK (perfil IN ('ADMIN', 'LIDER', 'MEMBRO', 'MUSICO')),
  CONSTRAINT fk_usuarios_ministerios
    FOREIGN KEY (ministerio_id) REFERENCES ministerios(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS escalas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(140) NOT NULL,
  status VARCHAR(30) NOT NULL,
  observacoes VARCHAR(600),
  ministerio_id BIGINT,
  CONSTRAINT chk_escalas_status
    CHECK (status IN ('CANCELADA', 'CONCLUIDA', 'PUBLICADA', 'RASCUNHO')),
  CONSTRAINT fk_escalas_ministerios
    FOREIGN KEY (ministerio_id) REFERENCES ministerios(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS repertorios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(140) NOT NULL,
  descricao VARCHAR(500),
  ministerio_id BIGINT,
  CONSTRAINT fk_repertorios_ministerios
    FOREIGN KEY (ministerio_id) REFERENCES ministerios(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS escala_musicas (
  escala_id BIGINT NOT NULL,
  musica_id BIGINT NOT NULL,
  PRIMARY KEY (escala_id, musica_id),
  CONSTRAINT fk_escala_musicas_escalas
    FOREIGN KEY (escala_id) REFERENCES escalas(id) ON DELETE CASCADE,
  CONSTRAINT fk_escala_musicas_musicas
    FOREIGN KEY (musica_id) REFERENCES musicas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS escala_usuarios (
  escala_id BIGINT NOT NULL,
  usuario_id BIGINT NOT NULL,
  PRIMARY KEY (escala_id, usuario_id),
  CONSTRAINT fk_escala_usuarios_escalas
    FOREIGN KEY (escala_id) REFERENCES escalas(id) ON DELETE CASCADE,
  CONSTRAINT fk_escala_usuarios_usuarios
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS repertorio_musicas (
  repertorio_id BIGINT NOT NULL,
  musica_id BIGINT NOT NULL,
  PRIMARY KEY (repertorio_id, musica_id),
  CONSTRAINT fk_repertorio_musicas_repertorios
    FOREIGN KEY (repertorio_id) REFERENCES repertorios(id) ON DELETE CASCADE,
  CONSTRAINT fk_repertorio_musicas_musicas
    FOREIGN KEY (musica_id) REFERENCES musicas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS usuario_musicas_favoritas (
  usuario_id BIGINT NOT NULL,
  musica_id BIGINT NOT NULL,
  PRIMARY KEY (usuario_id, musica_id),
  CONSTRAINT fk_usuario_favoritos_usuarios
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  CONSTRAINT fk_usuario_favoritos_musicas
    FOREIGN KEY (musica_id) REFERENCES musicas(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_escalas_status ON escalas(status);
CREATE INDEX IF NOT EXISTS idx_escalas_ministerio_id ON escalas(ministerio_id);
CREATE INDEX IF NOT EXISTS idx_escala_musicas_musica_id ON escala_musicas(musica_id);
CREATE INDEX IF NOT EXISTS idx_escala_usuarios_usuario_id ON escala_usuarios(usuario_id);
CREATE INDEX IF NOT EXISTS idx_musicas_titulo ON musicas(titulo);
CREATE INDEX IF NOT EXISTS idx_musicas_ministerio_id ON musicas(ministerio_id);
CREATE INDEX IF NOT EXISTS idx_repertorios_ministerio_id ON repertorios(ministerio_id);
CREATE INDEX IF NOT EXISTS idx_repertorio_musicas_musica_id ON repertorio_musicas(musica_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_perfil ON usuarios(perfil);
CREATE INDEX IF NOT EXISTS idx_usuarios_reset_token_hash ON usuarios(reset_token_hash);
CREATE INDEX IF NOT EXISTS idx_usuarios_api_token_hash ON usuarios(api_token_hash);
CREATE INDEX IF NOT EXISTS idx_usuarios_ministerio_id ON usuarios(ministerio_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_status_ministerio ON usuarios(status_ministerio);
CREATE INDEX IF NOT EXISTS idx_usuario_favoritos_musica_id ON usuario_musicas_favoritas(musica_id);

COMMIT;