-- WorshipFlow - seed complementar convertido para PostgreSQL/Supabase
-- Origem: database/2026-06-21-seed-100-musicas-usuarios.sql
-- Senha padrao dos usuarios ficticios: Worship@123

BEGIN;

INSERT INTO musicas (id, titulo, artista, tonalidade, bpm, link_cifra, ministerio_id) VALUES
(1001, 'Lugar Secreto', 'Gabriela Rocha', 'Am', 74, 'https://www.cifraclub.com.br/gabriela-rocha/lugar-secreto/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1002, 'Ousado Amor', 'Isaias Saad', 'G', 72, 'https://www.cifraclub.com.br/isaias-saad/ousado-amor/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1003, 'Preciso de Ti', 'Diante do Trono', 'A', 68, 'https://www.cifraclub.com.br/diante-do-trono/preciso-de-ti/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1004, 'Galileu', 'Fernandinho', 'D', 74, 'https://www.cifraclub.com.br/fernandinho/galileu/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1005, 'Santo Pra Sempre', 'Gabriel Guedes', 'Db', 72, 'https://www.cifraclub.com.br/gabriel-guedes/santo-pra-sempre/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1006, 'Fe', 'Florianopolis House of Prayer', 'C#m', 78, 'https://www.cifraclub.com.br/florianopolis-house-of-prayer/fe/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1007, 'Eu Navegarei', 'Gabriela Rocha', 'Em', 68, 'https://www.cifraclub.com.br/gabriela-rocha/eu-navegarei/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1008, 'Ninguem Explica Deus', 'Preto No Branco', 'G', 72, 'https://www.cifraclub.com.br/preto-no-branco/ninguem-explica-deus/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1009, 'A Ele a Gloria', 'Gabriela Rocha', 'G', 70, 'https://www.cifraclub.com.br/gabriela-rocha/a-ele-a-gloria/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1010, 'Me Atraiu', 'Gabriela Rocha', 'E', 68, 'https://www.cifraclub.com.br/gabriela-rocha/me-atraiu/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1011, 'Atos 2', 'Gabriela Rocha', 'D', 72, 'https://www.cifraclub.com.br/gabriela-rocha/atos-2/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1012, 'Vida Aos Sepulcros', 'Gabriela Rocha', 'B', 76, 'https://www.cifraclub.com.br/gabriela-rocha/vida-aos-sepulcros/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1013, 'Todavia Me Alegrarei', 'Samuel Messias', 'D', 82, 'https://www.cifraclub.com.br/samuel-messias/todavia-me-alegrarei/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1014, 'Deus Provera', 'Gabriela Gomes', 'A', 72, 'https://www.cifraclub.com.br/gabriela-gomes/deus-provera/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1015, 'Hey Pai', 'Isadora Pompeo', 'G', 78, 'https://www.cifraclub.com.br/isadora-pompeo/hey-pai/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1016, 'Faz Chover', 'Fernandinho', 'D', 72, 'https://www.cifraclub.com.br/fernandinho/faz-chover/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1017, 'Uma Nova Historia', 'Fernandinho', 'A', 76, 'https://www.cifraclub.com.br/fernandinho/uma-nova-historia/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1018, 'Grandes Coisas', 'Fernandinho', 'G', 78, 'https://www.cifraclub.com.br/fernandinho/grandes-coisas/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1019, 'Todas as Coisas', 'Fernandinho', 'D', 74, 'https://www.cifraclub.com.br/fernandinho/todas-as-coisas/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1020, 'Teus Sonhos', 'Fernandinho', 'A', 72, 'https://www.cifraclub.com.br/fernandinho/teus-sonhos/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1021, 'Yeshua', 'Fernandinho', 'Em', 68, 'https://www.cifraclub.com.br/fernandinho/yeshua/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1022, 'Nada Alem do Sangue', 'Fernandinho', 'G', 70, 'https://www.cifraclub.com.br/fernandinho/nada-alem-do-sangue/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1023, 'Caia Fogo', 'Fernandinho', 'D', 82, 'https://www.cifraclub.com.br/fernandinho/caia-fogo/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1024, 'Unico', 'Fernandinho', 'C', 72, 'https://www.cifraclub.com.br/fernandinho/unico/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1025, 'Ainda Que a Figueira', 'Fernandinho', 'G', 70, 'https://www.cifraclub.com.br/fernandinho/ainda-que-a-figueira/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1026, 'Aclame Ao Senhor', 'Diante do Trono', 'A', 72, 'https://www.cifraclub.com.br/diante-do-trono/aclama-ao-senhor/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1027, 'Aguas Purificadoras', 'Diante do Trono', 'G', 76, 'https://www.cifraclub.com.br/diante-do-trono/aguas-purificadoras/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1028, 'Nos Bracos do Pai', 'Diante do Trono', 'E', 68, 'https://www.cifraclub.com.br/diante-do-trono/nos-bracos-do-pai/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1029, 'Manancial', 'Diante do Trono', 'D', 70, 'https://www.cifraclub.com.br/diante-do-trono/manancial/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1030, 'Quero Me Apaixonar', 'Diante do Trono', 'A', 72, 'https://www.cifraclub.com.br/diante-do-trono/quero-me-apaixonar/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1031, 'Me Ama', 'Diante do Trono', 'C', 70, 'https://www.cifraclub.com.br/diante-do-trono/me-ama/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1032, 'Escudo', 'Diante do Trono', 'G', 74, 'https://www.cifraclub.com.br/diante-do-trono/escudo/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1033, 'Exaltado', 'Diante do Trono', 'A', 78, 'https://www.cifraclub.com.br/diante-do-trono/exaltado/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1034, 'Tu Reinas', 'Diante do Trono', 'D', 76, 'https://www.cifraclub.com.br/diante-do-trono/tu-reinas/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1035, 'Creio', 'Diante do Trono', 'G', 78, 'https://www.cifraclub.com.br/diante-do-trono/creio/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1036, 'Ressuscita-me', 'Aline Barros', 'A', 72, 'https://www.cifraclub.com.br/aline-barros/ressuscita-me/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1037, 'Sonda-me Usa-me', 'Aline Barros', 'D', 74, 'https://www.cifraclub.com.br/aline-barros/sonda-me-usa-me/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1038, 'Casa do Pai', 'Aline Barros', 'G', 76, 'https://www.cifraclub.com.br/aline-barros/casa-do-pai/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1039, 'Consagracao', 'Aline Barros', 'E', 82, 'https://www.cifraclub.com.br/aline-barros/consagracao/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1040, 'Autor da Vida', 'Aline Barros', 'D', 76, 'https://www.cifraclub.com.br/aline-barros/autor-da-vida/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1041, 'Recomecar', 'Aline Barros', 'A', 72, 'https://www.cifraclub.com.br/aline-barros/recomecar/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1042, 'Santidade', 'Aline Barros', 'C', 70, 'https://www.cifraclub.com.br/aline-barros/santidade/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1043, 'Caminho de Milagres', 'Aline Barros', 'D', 76, 'https://www.cifraclub.com.br/aline-barros/caminho-de-milagres/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1044, 'Bem Mais Que Tudo', 'Aline Barros', 'G', 72, 'https://www.cifraclub.com.br/aline-barros/bem-mais-que-tudo/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1045, 'Deus do Impossivel', 'Aline Barros', 'E', 70, 'https://www.cifraclub.com.br/aline-barros/deus-do-impossivel/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1046, 'E Tudo Sobre Voce', 'Morada', 'E', 70, 'https://www.cifraclub.com.br/morada/e-tudo-sobre-voce/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1047, 'Para Que Entre o Rei', 'Morada', 'D', 74, 'https://www.cifraclub.com.br/morada/para-que-entre-o-rei/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1048, 'Uma Coisa', 'Morada', 'G', 68, 'https://www.cifraclub.com.br/morada/uma-coisa/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1049, 'So Tu Es Santo', 'Morada', 'A', 72, 'https://www.cifraclub.com.br/morada/so-tu-es-santo/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1050, 'Nao Temerei', 'Morada', 'C', 78, 'https://www.cifraclub.com.br/morada/nao-temerei/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1051, 'Deixa Queimar', 'Morada', 'D', 80, 'https://www.cifraclub.com.br/morada/deixa-queimar/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1052, 'Puro e Simples', 'Morada', 'G', 72, 'https://www.cifraclub.com.br/morada/puro-e-simples/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1053, 'Ele E', 'Morada', 'E', 74, 'https://www.cifraclub.com.br/morada/ele-e/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1054, 'Cordeiro e Leao', 'Morada', 'D', 78, 'https://www.cifraclub.com.br/morada/cordeiro-e-leao/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1055, 'A Casa e Sua', 'Casa Worship', 'C', 72, 'https://www.cifraclub.com.br/casa-worship/a-casa-e-sua/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1056, 'Era Eu', 'Casa Worship', 'G', 74, 'https://www.cifraclub.com.br/casa-worship/era-eu/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1057, 'Yeshua', 'Casa Worship', 'Em', 68, 'https://www.cifraclub.com.br/casa-worship/yeshua/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1058, 'Vento Impetuoso', 'Casa Worship', 'A', 78, 'https://www.cifraclub.com.br/casa-worship/vento-impetuoso/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1059, 'Algo Novo', 'Kemuel', 'D', 76, 'https://www.cifraclub.com.br/kemuel/algo-novo/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1060, 'O Teu Amor', 'Kemuel', 'G', 72, 'https://www.cifraclub.com.br/kemuel/o-teu-amor/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1061, 'Que Amor E Esse', 'Luma Elpidio', 'G', 72, 'https://www.cifraclub.com.br/luma-elpidio/que-amor-e-esse/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1062, 'Liberta-me de Mim', 'Luma Elpidio', 'E', 70, 'https://www.cifraclub.com.br/luma-elpidio/liberta-me-de-mim/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1063, 'Sou Casa', 'Luma Elpidio', 'D', 74, 'https://www.cifraclub.com.br/luma-elpidio/sou-casa/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1064, 'Bondade de Deus', 'Isaias Saad', 'G', 72, 'https://www.cifraclub.com.br/isaias-saad/bondade-de-deus/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1065, 'Ruja o Leao', 'Talita Catanzaro', 'Em', 78, 'https://www.cifraclub.com.br/talita-catanzaro/ruja-o-leao/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1066, 'Enche-me', 'Isaias Saad', 'A', 70, 'https://www.cifraclub.com.br/isaias-saad/enche-me/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1067, 'Espirito Vem', 'Isaias Saad', 'D', 72, 'https://www.cifraclub.com.br/isaias-saad/espirito-vem/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1068, 'De Dentro Pra Fora', 'Julia Vitoria', 'A', 76, 'https://www.cifraclub.com.br/julia-vitoria/de-dentro-pra-fora/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1069, 'Alem do Rio Azul', 'Julia Vitoria', 'G', 72, 'https://www.cifraclub.com.br/julia-vitoria/alem-do-rio-azul/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1070, 'Reina Sobre Mim', 'Nivea Soares', 'D', 74, 'https://www.cifraclub.com.br/nivea-soares/reina-sobre-mim/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1071, 'Que Se Abram os Ceus', 'Nivea Soares', 'G', 76, 'https://www.cifraclub.com.br/nivea-soares/que-se-abram-os-ceus/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1072, 'Teu Amor Nao Falha', 'Nivea Soares', 'A', 72, 'https://www.cifraclub.com.br/nivea-soares/teu-amor-nao-falha/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1073, 'Vai Valer a Pena', 'Livres Para Adorar', 'G', 76, 'https://www.cifraclub.com.br/livres-para-adorar/vai-valer-a-pena/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1074, 'Lindo Es', 'Livres Para Adorar', 'D', 72, 'https://www.cifraclub.com.br/livres-para-adorar/lindo-es/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1075, 'Mais Perto', 'Livres Para Adorar', 'E', 70, 'https://www.cifraclub.com.br/livres-para-adorar/mais-perto/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1076, 'Oh Quao Lindo Esse Nome E', 'Ana Nobrega', 'D', 72, 'https://www.cifraclub.com.br/ana-nobrega/quao-lindo-esse-nome-e/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1077, 'Quando Ele Vem', 'Ana Nobrega', 'C', 70, 'https://www.cifraclub.com.br/ana-nobrega/quando-ele-vem/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1078, 'Oceanos', 'Ana Nobrega', 'D', 68, 'https://www.cifraclub.com.br/ana-nobrega/oceanos/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1079, 'Tu Es Bom', 'Ministerio Pedras Vivas', 'A', 78, 'https://www.cifraclub.com.br/ministerio-pedras-vivas/tu-es-bom/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1080, 'Rompendo em Fe', 'Comunidade Evangelica de Maringa', 'E', 76, 'https://www.cifraclub.com.br/comunidade-evangelica-de-maringa/rompendo-em-fe/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1081, 'O Escudo', 'Voz da Verdade', 'G', 74, 'https://www.cifraclub.com.br/voz-da-verdade/o-escudo/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1082, 'Deus Cuida de Mim', 'Kleber Lucas', 'C', 72, 'https://www.cifraclub.com.br/kleber-lucas/deus-cuida-de-mim/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1083, 'Aos Pes da Cruz', 'Kleber Lucas', 'D', 70, 'https://www.cifraclub.com.br/kleber-lucas/aos-pes-da-cruz/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1084, 'Sobre a Graca', 'Paulo Cesar Baruk', 'A', 72, 'https://www.cifraclub.com.br/paulo-cesar-baruk/sobre-a-graca/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1085, 'Ele Continua Sendo Bom', 'Paulo Cesar Baruk', 'G', 74, 'https://www.cifraclub.com.br/paulo-cesar-baruk/ele-continua-sendo-bom/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1086, 'Aquieta Minhalma', 'Ministerio Zoe', 'D', 68, 'https://www.cifraclub.com.br/ministerio-zoe/aquieta-minhalma/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1087, 'Ha Um Lugar', 'Heloisa Rosa', 'E', 70, 'https://www.cifraclub.com.br/heloisa-rosa/ha-um-lugar/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1088, 'Jesus e o Caminho', 'Heloisa Rosa', 'G', 72, 'https://www.cifraclub.com.br/heloisa-rosa/jesus-e-o-caminho/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1089, 'Grande e o Senhor', 'Adhemar de Campos', 'A', 76, 'https://www.cifraclub.com.br/adhemar-de-campos/grande-e-o-senhor/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1090, 'Nosso General', 'Adhemar de Campos', 'Em', 78, 'https://www.cifraclub.com.br/adhemar-de-campos/nosso-general/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1091, 'Ao Unico', 'Vencedores Por Cristo', 'D', 74, 'https://www.cifraclub.com.br/vencedores-por-cristo/ao-unico/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1092, 'Deus Somente Deus', 'Vencedores Por Cristo', 'G', 70, 'https://www.cifraclub.com.br/vencedores-por-cristo/deus-somente-deus/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1093, 'Raridade', 'Anderson Freire', 'G', 72, 'https://www.cifraclub.com.br/anderson-freire/raridade/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1094, 'Acalma o Meu Coracao', 'Anderson Freire', 'C', 68, 'https://www.cifraclub.com.br/anderson-freire/acalma-o-meu-coracao/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1095, 'Advogado Fiel', 'Bruna Karla', 'D', 70, 'https://www.cifraclub.com.br/bruna-karla/advogado-fiel/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1096, 'Sou Humano', 'Bruna Karla', 'A', 72, 'https://www.cifraclub.com.br/bruna-karla/sou-humano/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1097, '500 Graus', 'Cassiane', 'G', 84, 'https://www.cifraclub.com.br/cassiane/500-graus/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1098, 'Com Muito Louvor', 'Cassiane', 'E', 82, 'https://www.cifraclub.com.br/cassiane/com-muito-louvor/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1099, 'Deus e Deus', 'Delino Marcal', 'D', 72, 'https://www.cifraclub.com.br/delino-marcal/deus-e-deus/', (SELECT id FROM ministerios ORDER BY id LIMIT 1)),
(1100, 'O Segredo', 'Leandro Borges', 'C', 70, 'https://www.cifraclub.com.br/leandro-borges/o-segredo/', (SELECT id FROM ministerios ORDER BY id LIMIT 1))
ON CONFLICT (id) DO NOTHING;

INSERT INTO usuarios (
  id, nome, habilidades, status_ministerio, email, senha_hash, telefone,
  instrumento_principal, perfil, reset_token_hash, reset_token_expira_em,
  api_token_hash, api_token_expira_em, foto_perfil, foto_perfil_tipo, ministerio_id
)
SELECT
  2000 + seq.n AS id,
  'Membro Worship ' || LPAD(seq.n::TEXT, 3, '0') AS nome,
  'Disponivel para escalas, ensaios e repertorio. Perfil seed ' || LPAD(seq.n::TEXT, 3, '0') AS habilidades,
  'ATIVO' AS status_ministerio,
  'membro' || LPAD(seq.n::TEXT, 3, '0') || '@worshipflow.local' AS email,
  '$2a$10$BrPoknQJkcr8m.CYeTBWiuyGM9/6W/Psc1Mx7d.poBxmA9EkHEdNO' AS senha_hash,
  '(11) 9' || LPAD((70000000 + seq.n)::TEXT, 8, '0') AS telefone,
  (ARRAY['Vocal', 'Violao', 'Guitarra', 'Teclado', 'Baixo', 'Bateria', 'Saxofone', 'Percussao', 'Backing Vocal', 'Violino', 'Cajon', 'Midias'])[((seq.n - 1) % 12) + 1] AS instrumento_principal,
  CASE
    WHEN seq.n % 20 = 0 THEN 'LIDER'
    WHEN seq.n % 7 = 0 THEN 'MUSICO'
    ELSE 'MEMBRO'
  END AS perfil,
  NULL AS reset_token_hash,
  NULL::TIMESTAMP AS reset_token_expira_em,
  NULL AS api_token_hash,
  NULL::TIMESTAMP AS api_token_expira_em,
  NULL AS foto_perfil,
  NULL AS foto_perfil_tipo,
  (SELECT id FROM ministerios ORDER BY id LIMIT 1) AS ministerio_id
FROM generate_series(1, 100) AS seq(n)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('musicas', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM musicas), 1100), TRUE);
SELECT setval(pg_get_serial_sequence('usuarios', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM usuarios), 2100), TRUE);

COMMIT;