-- WorshipFlow - refatoracao do schema PostgreSQL preservando registros de musicas.
--
-- Objetivo:
-- 1. Alinhar o banco antigo ao modelo atual das entidades Spring Boot.
-- 2. Preservar todos os registros existentes em public.musicas.
-- 3. Remover registros operacionais das demais tabelas quando isso nao quebra
--    a integridade das musicas preservadas.
--
-- Observacao importante:
-- - Registros de ministerios referenciados por musicas precisam ser mantidos.
--   Apagar esses ministerios obrigaria alterar musicas.ministerio_id, o que
--   violaria a regra de nao mexer nos registros da tabela musicas.

begin;

set search_path to public;

create table if not exists ministerios (
    id bigint generated by default as identity,
    nome varchar(120) not null,
    descricao varchar(500),
    ativo boolean not null default true
);

create table if not exists musicas (
    id bigint generated by default as identity,
    titulo varchar(140) not null,
    artista varchar(120),
    tonalidade varchar(12),
    bpm integer,
    link_cifra varchar(500),
    ministerio_id bigint
);

create table if not exists usuarios (
    id bigint generated by default as identity,
    nome varchar(120) not null,
    email varchar(160) not null,
    senha_hash varchar(255) not null,
    telefone varchar(30),
    instrumento_principal varchar(80),
    habilidades varchar(300),
    status_ministerio varchar(30) not null default 'ATIVO',
    perfil varchar(30) not null default 'USER',
    reset_token_hash varchar(128),
    reset_token_expira_em timestamp,
    api_token_hash varchar(128),
    api_token_expira_em timestamp,
    foto_perfil text,
    foto_perfil_tipo varchar(60),
    ministerio_id bigint
);

create table if not exists escalas (
    id bigint generated by default as identity,
    titulo varchar(140) not null,
    data_escala date,
    status varchar(30) not null default 'RASCUNHO',
    observacoes varchar(600),
    funcoes_usuarios varchar(2000),
    ministerio_id bigint
);

create table if not exists repertorios (
    id bigint generated by default as identity,
    nome varchar(140) not null,
    descricao varchar(500),
    ministerio_id bigint
);

create table if not exists escala_musicas (
    escala_id bigint not null,
    musica_id bigint not null
);

create table if not exists escala_usuarios (
    escala_id bigint not null,
    usuario_id bigint not null
);

create table if not exists repertorio_musicas (
    repertorio_id bigint not null,
    musica_id bigint not null
);

create table if not exists usuario_musicas_favoritas (
    usuario_id bigint not null,
    musica_id bigint not null
);

alter table ministerios
    add column if not exists nome varchar(120),
    add column if not exists descricao varchar(500),
    add column if not exists ativo boolean;

alter table musicas
    add column if not exists titulo varchar(140),
    add column if not exists artista varchar(120),
    add column if not exists tonalidade varchar(12),
    add column if not exists bpm integer,
    add column if not exists link_cifra varchar(500),
    add column if not exists ministerio_id bigint;

alter table usuarios
    add column if not exists nome varchar(120),
    add column if not exists email varchar(160),
    add column if not exists senha_hash varchar(255),
    add column if not exists telefone varchar(30),
    add column if not exists instrumento_principal varchar(80),
    add column if not exists habilidades varchar(300),
    add column if not exists status_ministerio varchar(30),
    add column if not exists perfil varchar(30),
    add column if not exists reset_token_hash varchar(128),
    add column if not exists reset_token_expira_em timestamp,
    add column if not exists api_token_hash varchar(128),
    add column if not exists api_token_expira_em timestamp,
    add column if not exists foto_perfil text,
    add column if not exists foto_perfil_tipo varchar(60),
    add column if not exists ministerio_id bigint;

alter table escalas
    add column if not exists titulo varchar(140),
    add column if not exists data_escala date,
    add column if not exists status varchar(30),
    add column if not exists observacoes varchar(600),
    add column if not exists funcoes_usuarios varchar(2000),
    add column if not exists ministerio_id bigint;

alter table repertorios
    add column if not exists nome varchar(140),
    add column if not exists descricao varchar(500),
    add column if not exists ministerio_id bigint;

alter table escala_musicas
    add column if not exists escala_id bigint,
    add column if not exists musica_id bigint;

alter table escala_usuarios
    add column if not exists escala_id bigint,
    add column if not exists usuario_id bigint;

alter table repertorio_musicas
    add column if not exists repertorio_id bigint,
    add column if not exists musica_id bigint;

alter table usuario_musicas_favoritas
    add column if not exists usuario_id bigint,
    add column if not exists musica_id bigint;

alter table ministerios
    alter column id type bigint using id::bigint,
    alter column nome type varchar(120),
    alter column descricao type varchar(500),
    alter column ativo type boolean using coalesce(ativo, true);

alter table musicas
    alter column id type bigint using id::bigint,
    alter column titulo type varchar(140),
    alter column artista type varchar(120),
    alter column tonalidade type varchar(12),
    alter column bpm type integer using bpm::integer,
    alter column link_cifra type varchar(500),
    alter column ministerio_id type bigint using ministerio_id::bigint;

alter table usuarios
    alter column id type bigint using id::bigint,
    alter column nome type varchar(120),
    alter column email type varchar(160),
    alter column senha_hash type varchar(255),
    alter column telefone type varchar(30),
    alter column instrumento_principal type varchar(80),
    alter column habilidades type varchar(300),
    alter column status_ministerio type varchar(30),
    alter column perfil type varchar(30),
    alter column reset_token_hash type varchar(128),
    alter column reset_token_expira_em type timestamp using reset_token_expira_em::timestamp,
    alter column api_token_hash type varchar(128),
    alter column api_token_expira_em type timestamp using api_token_expira_em::timestamp,
    alter column foto_perfil type text,
    alter column foto_perfil_tipo type varchar(60),
    alter column ministerio_id type bigint using ministerio_id::bigint;

alter table escalas
    alter column id type bigint using id::bigint,
    alter column titulo type varchar(140),
    alter column data_escala type date using data_escala::date,
    alter column status type varchar(30),
    alter column observacoes type varchar(600),
    alter column funcoes_usuarios type varchar(2000),
    alter column ministerio_id type bigint using ministerio_id::bigint;

alter table repertorios
    alter column id type bigint using id::bigint,
    alter column nome type varchar(140),
    alter column descricao type varchar(500),
    alter column ministerio_id type bigint using ministerio_id::bigint;

alter table escala_musicas
    alter column escala_id type bigint using escala_id::bigint,
    alter column musica_id type bigint using musica_id::bigint;

alter table escala_usuarios
    alter column escala_id type bigint using escala_id::bigint,
    alter column usuario_id type bigint using usuario_id::bigint;

alter table repertorio_musicas
    alter column repertorio_id type bigint using repertorio_id::bigint,
    alter column musica_id type bigint using musica_id::bigint;

alter table usuario_musicas_favoritas
    alter column usuario_id type bigint using usuario_id::bigint,
    alter column musica_id type bigint using musica_id::bigint;

-- Limpeza de registros permitida. A ordem evita cascatas acidentais sobre musicas.
delete from usuario_musicas_favoritas;
delete from escala_musicas;
delete from escala_usuarios;
delete from repertorio_musicas;
delete from escalas;
delete from repertorios;
delete from usuarios;
delete from ministerios m
where not exists (
    select 1
    from musicas mu
    where mu.ministerio_id = m.id
);

update ministerios set nome = 'Ministerio sem nome' where nome is null;
update ministerios set ativo = true where ativo is null;

alter table ministerios alter column ativo set default true;
alter table usuarios alter column status_ministerio set default 'ATIVO';
alter table usuarios alter column perfil set default 'USER';
alter table escalas alter column status set default 'RASCUNHO';

do $$
begin
    if not exists (select 1 from musicas where titulo is null) then
        alter table musicas alter column titulo set not null;
    else
        raise notice 'Nao foi aplicado NOT NULL em musicas.titulo porque existem musicas com titulo nulo.';
    end if;

    alter table ministerios alter column nome set not null;
    alter table ministerios alter column ativo set not null;
    alter table usuarios alter column nome set not null;
    alter table usuarios alter column email set not null;
    alter table usuarios alter column senha_hash set not null;
    alter table usuarios alter column status_ministerio set not null;
    alter table usuarios alter column perfil set not null;
    alter table escalas alter column titulo set not null;
    alter table escalas alter column status set not null;
    alter table repertorios alter column nome set not null;
end $$;

create or replace function pg_temp.wf_ensure_id_sequence(p_table regclass, p_column name)
returns void
language plpgsql
as $$
declare
    v_schema_name name;
    v_table_name name;
    v_table_ref text;
    v_sequence_name name;
    v_sequence_ref text;
    v_is_identity text;
    v_column_default text;
    v_max_id bigint;
begin
    select n.nspname, c.relname
      into v_schema_name, v_table_name
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
     where c.oid = p_table;

    v_table_ref := format('%I.%I', v_schema_name, v_table_name);
    v_sequence_name := v_table_name || '_' || p_column || '_seq';
    v_sequence_ref := format('%I.%I', v_schema_name, v_sequence_name);

    select attidentity
      into v_is_identity
      from pg_attribute
     where attrelid = p_table
       and attname = p_column
       and not attisdropped;

    if v_is_identity in ('a', 'd') then
        return;
    end if;

    select column_default
      into v_column_default
      from information_schema.columns
     where table_schema = v_schema_name
       and table_name = v_table_name
       and column_name = p_column;

    if v_column_default is not null and v_column_default like 'nextval(%' then
        execute format('select coalesce(max(%I), 0) from %s', p_column, v_table_ref)
           into v_max_id;
        execute format('select setval(pg_get_serial_sequence(%L, %L), %s, %s)',
                       v_table_ref,
                       p_column,
                       greatest(v_max_id, 1),
                       case when v_max_id > 0 then 'true' else 'false' end);
        return;
    end if;

    execute format('create sequence if not exists %s', v_sequence_ref);
    execute format('alter sequence %s owned by %s.%I', v_sequence_ref, v_table_ref, p_column);
    execute format('alter table %s alter column %I set default nextval(%L::regclass)',
                   v_table_ref,
                   p_column,
                   v_sequence_ref);
    execute format('select coalesce(max(%I), 0) from %s', p_column, v_table_ref)
       into v_max_id;
    execute format('select setval(%L::regclass, %s, %s)',
                   v_sequence_ref,
                   greatest(v_max_id, 1),
                   case when v_max_id > 0 then 'true' else 'false' end);
end $$;

select pg_temp.wf_ensure_id_sequence('ministerios'::regclass, 'id');
select pg_temp.wf_ensure_id_sequence('musicas'::regclass, 'id');
select pg_temp.wf_ensure_id_sequence('usuarios'::regclass, 'id');
select pg_temp.wf_ensure_id_sequence('escalas'::regclass, 'id');
select pg_temp.wf_ensure_id_sequence('repertorios'::regclass, 'id');

do $$
declare
    r record;
begin
    for r in
        select conrelid::regclass as table_name, conname
          from pg_constraint
         where contype = 'f'
           and conrelid in (
                'musicas'::regclass,
                'usuarios'::regclass,
                'escalas'::regclass,
                'repertorios'::regclass,
                'escala_musicas'::regclass,
                'escala_usuarios'::regclass,
                'repertorio_musicas'::regclass,
                'usuario_musicas_favoritas'::regclass
           )
    loop
        execute format('alter table %s drop constraint if exists %I', r.table_name, r.conname);
    end loop;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conrelid = 'ministerios'::regclass and contype = 'p') then
        alter table ministerios add constraint ministerios_pkey primary key (id);
    end if;

    if not exists (select 1 from pg_constraint where conrelid = 'musicas'::regclass and contype = 'p') then
        alter table musicas add constraint musicas_pkey primary key (id);
    end if;

    if not exists (select 1 from pg_constraint where conrelid = 'usuarios'::regclass and contype = 'p') then
        alter table usuarios add constraint usuarios_pkey primary key (id);
    end if;

    if not exists (select 1 from pg_constraint where conrelid = 'escalas'::regclass and contype = 'p') then
        alter table escalas add constraint escalas_pkey primary key (id);
    end if;

    if not exists (select 1 from pg_constraint where conrelid = 'repertorios'::regclass and contype = 'p') then
        alter table repertorios add constraint repertorios_pkey primary key (id);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'usuarios_email_key') then
        alter table usuarios add constraint usuarios_email_key unique (email);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'escala_musicas_pkey') then
        alter table escala_musicas add constraint escala_musicas_pkey primary key (escala_id, musica_id);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'escala_usuarios_pkey') then
        alter table escala_usuarios add constraint escala_usuarios_pkey primary key (escala_id, usuario_id);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'repertorio_musicas_pkey') then
        alter table repertorio_musicas add constraint repertorio_musicas_pkey primary key (repertorio_id, musica_id);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'usuario_musicas_favoritas_pkey') then
        alter table usuario_musicas_favoritas add constraint usuario_musicas_favoritas_pkey primary key (usuario_id, musica_id);
    end if;
end $$;

alter table musicas
    add constraint fk_musicas_ministerio
    foreign key (ministerio_id)
    references ministerios(id)
    on delete set null
    not valid;

alter table usuarios
    add constraint fk_usuarios_ministerio
    foreign key (ministerio_id)
    references ministerios(id)
    on delete set null;

alter table escalas
    add constraint fk_escalas_ministerio
    foreign key (ministerio_id)
    references ministerios(id)
    on delete set null;

alter table repertorios
    add constraint fk_repertorios_ministerio
    foreign key (ministerio_id)
    references ministerios(id)
    on delete set null;

alter table escala_musicas
    add constraint fk_escala_musicas_escala
    foreign key (escala_id)
    references escalas(id)
    on delete cascade,
    add constraint fk_escala_musicas_musica
    foreign key (musica_id)
    references musicas(id)
    on delete cascade;

alter table escala_usuarios
    add constraint fk_escala_usuarios_escala
    foreign key (escala_id)
    references escalas(id)
    on delete cascade,
    add constraint fk_escala_usuarios_usuario
    foreign key (usuario_id)
    references usuarios(id)
    on delete cascade;

alter table repertorio_musicas
    add constraint fk_repertorio_musicas_repertorio
    foreign key (repertorio_id)
    references repertorios(id)
    on delete cascade,
    add constraint fk_repertorio_musicas_musica
    foreign key (musica_id)
    references musicas(id)
    on delete cascade;

alter table usuario_musicas_favoritas
    add constraint fk_usuario_musicas_favoritas_usuario
    foreign key (usuario_id)
    references usuarios(id)
    on delete cascade,
    add constraint fk_usuario_musicas_favoritas_musica
    foreign key (musica_id)
    references musicas(id)
    on delete cascade;

create index if not exists idx_musicas_ministerio_id on musicas (ministerio_id);
create index if not exists idx_usuarios_ministerio_id on usuarios (ministerio_id);
create index if not exists idx_escalas_ministerio_id on escalas (ministerio_id);
create index if not exists idx_repertorios_ministerio_id on repertorios (ministerio_id);
create index if not exists idx_escala_musicas_musica_id on escala_musicas (musica_id);
create index if not exists idx_escala_usuarios_usuario_id on escala_usuarios (usuario_id);
create index if not exists idx_repertorio_musicas_musica_id on repertorio_musicas (musica_id);
create index if not exists idx_usuario_musicas_favoritas_musica_id on usuario_musicas_favoritas (musica_id);

-- Validacao segura: nao altera musicas. Se houver musicas com ministerio_id invalido,
-- a FK fica NOT VALID, mas novos dados passam a ser protegidos.
do $$
begin
    if not exists (
        select 1
          from musicas mu
         where mu.ministerio_id is not null
           and not exists (
                select 1
                  from ministerios m
                 where m.id = mu.ministerio_id
           )
    ) then
        alter table musicas validate constraint fk_musicas_ministerio;
    else
        raise notice 'fk_musicas_ministerio ficou NOT VALID porque existem musicas com ministerio_id sem ministerio correspondente.';
    end if;
end $$;

commit;
